### ISSUE TITLE
Change string "app_name" to something like "app_name_aboutbox"

### ISSUE THREAD

**Issue by duartebarbosadev** [eggheadgames/android-about-box#13]
Hi
That's because the about-box "app_name" is basically overriding mine and changing the app name etc...

Thanks 👍

**Comment by mikemee** [comment]
@PedroBarbosaPT hmm, that's strange. We should be using the one _from_ your app, not defining our own. What is it changing it to?  Perhaps there's a default somewhere we need to remove. I'll take a look. Thx!

**Comment by mikemee** [comment]
@PedroBarbosaPT I've just released version 1.0.2 that has a fix for this. Please give it a try and let me know if there is still a problem. Thanks!
