### ISSUE TITLE
We should be able to translate/change Words like "Version", "Contact Support" ...

### ISSUE THREAD

**Issue by duartebarbosadev** [eggheadgames/android-about-box#3]
Title^

Thanks

**Comment by mikemee** [comment]
Great idea! @PedroBarbosaPT Can you contribute a language if we get the words isolated?

**Comment by mikemee** [comment]
@PedroBarbosaPT I just double checked, and we have them isolated here:

https://github.com/eggheadgames/android-about-box/blob/develop/library/src/main/res/values/strings.xml

If you give us the translation of this file, we'll add it ourselves, or just provide a PR. Thanks!

**Comment by duartebarbosadev** [comment]
What does "Acknowledgment" suppose to be/do? (Diferent meanings)
That's Portuguese.
Be aware that most people like to use their own translation
[strings.zip](https://github.com/eggheadgames/android-about-box/files/762301/strings.zip)

**Comment by mikemee** [comment]
@PedroBarbosaPT Thanks!  I'll get those added.

> Be aware that most people like to use their own translation

Good point. I'll see if there's a convenient way to do this.

**Comment by mikemee** [comment]
@AlexDibrivnyy Let's start by adding the `strings.zip` file above for Portuguese (and add any languages you're familiar with too, thanks!) and then let's discuss a nice way to structure the API to allow them to be explicitly provided if people want to override the defaults.

**Comment by mikemee** [comment]
@PedroBarbosaPT "Acknowledgment" can be licenses that need to be included for 3rd party libraries, or, in our case, links to 3rd parties that we license puzzles from. Or it could just be "Thanks Mum and Dad!"

**Comment by mikemee** [comment]
@PedroBarbosaPT We integrated your strings (and added one that was machine translated).

Note, with Android you should be able to provide new strings in your app that replace those in the library. E.g. see https://stackoverflow.com/questions/4263259/replace-or-override-string-in-android-library-project#4383517.

In this next release we prefixed all the strings with `egab_` (Egghead Games About Box) to make sure there wouldn't be any unintentional conflicts with application code.
