### ISSUE TITLE
Copyright & Author & About Company

### ISSUE THREAD

**Issue by ethauvin** [eggheadgames/android-about-box#30]
I think the top section should include an `Author` and `Copyright` if specified. Thoughts?

The `About Company X`  should be optional if no `title` is set.

I can take a crack at the implementation, pretty straightforward.

**Comment by mikemee** [comment]
@ethauvin Agreed, thanks!

Some people will find that useful I'm sure (especially those that are a "person" rather than "a company").

**Comment by mikemee** [comment]
Closed by #31
