### ISSUE TITLE
Which activity to add in launch()?

### ISSUE THREAD

**Issue by Kvaibhav01** [eggheadgames/android-about-box#41]
I want to know which _activity_ should I add in `AboutActivity.launch(activity);`? Do I need to create an `intent` for it?

**Comment by AlexDibrivnyy** [comment]
Hi @Kvaibhav01 No, you no need to create a new activite or intent. You just need to put a context of your activity to this `lauch` method. AboutBox will use it to open About screen on the same process as your app. So, if your activity name is `MainActivity.class` then, for example, try to put to `onCreate(...)` method of `MainActivity` something like this `AboutActivity.launch(MainActivity.this);`

```
public class MainActivity extends Activity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
// in theory we will need to move this to some click listener, but for demo purposes this is ok.
        AboutActivity.launch(MainActivity.this);
    }
}

```

**Comment by mikemee** [comment]
@Kvaibhav01 Let us know if you still have remaining questions. Closing this now.
