### ISSUE TITLE
Adding other categories in the activity 

### ISSUE THREAD

**Issue by Kvaibhav01** [eggheadgames/android-about-box#43]
I'm completely new to this. I've added the about activity but I can't see the _Leave Review_, _Try Other Apps_, _About Egghead Games_, _Privacy Policy_ and _Acknowledgement_ categories! Do I need to implement them manually or there is a code for it?

**Comment by mikemee** [comment]
The readme has an example of this, as you likely noticed:
```java
        // app publisher for "Try Other Apps" item
        aboutConfig.appPublisher = APP_PUBLISHER;

        // if pages are stored locally, then you need to override aboutConfig.dialog to be able use custom WebView
        aboutConfig.companyHtmlPath = COMPANY_HTML_PATH;
        aboutConfig.privacyHtmlPath = PRIVACY_HTML_PATH;
        aboutConfig.acknowledgmentHtmlPath = ACKNOWLEDGMENT_HTML_PATH;
```
However, to make this more explicit, here are some of the constants we've defined for our Logic Puzzles app:
```java
    public static final String EMAIL_ADDRESS = "support@eggheadgames.com";

    private static final String LOG_UI_EVENT_NAME = "About";
    private static final String FACEBOOK_USER_NAME = "EggheadGames";
    private static final String TWITTER_USER_NAME = "eggheadgamesllc";
    private static final String WEB_HOME_PAGE = "https://eggheadgames.com/";
    private static final String APP_PUBLISHER = "\"Egghead Games\"";

    public static final String GUIDE_HTML_PATH = "file:///android_asset/html/help.html";
    public static final String COMPANY_HTML_PATH = "file:///android_asset/html/company.html";
    public static final String PRIVACY_HTML_PATH = "file:///android_asset/html/privacy.html";
    public static final String ACKNOWLEDGMENT_HTML_PATH = "file:///android_asset/html/acknowledgment.html";
```

I.e., so create a new folder `html` in the Android Assets location, put some html files there, and you should be ready to go.  The `APP_PUBLISHER` is something you get from Google Play.

Hope this helps!  Please re-open if you have more questions!

**Comment by Kvaibhav01** [comment]
What about Leave Review? How to implement that?

Also, when I tap on Privacy Policy/About/Acknowledgement nothing happens. Can you tell me more clearly what code should go inside:

```
 public void open(AppCompatActivity appCompatActivity, String url, String tag) {
               // handle custom implementations of WebView. It will be called when user click to web items. (Example: "Privacy", "Acknowledgments" and "About")
            }
```
I want to open some HTML files from internet (browser).

**Comment by mikemee** [comment]
> What about Leave Review?

If you set `aboutConfig.appPublisher` then it should be automatically added.

> when I tap on Privacy Policy/About/Acknowledgement nothing happens

Did you provide the HTML files in your app?  It is not designed to get them from the internet. See example above.
