### ISSUE TITLE
Twitter profile doesn't opens

### ISSUE THREAD

**Issue by Kvaibhav01** [eggheadgames/android-about-box#45]
When I tap on the Twitter list in the About activity, the Twitter app opens for a second, displays a toast **"Cannot load the user's info. Please try again."** How to resolve this? I've the following code line:

`private static final String TWITTER_USER_NAME = "@vaibhav_khulbe";` 
and it's used as: `aboutConfig.twitterUserName = TWITTER_USER_NAME;`

I've also tried adding the Twitter profile URL but it displays the same toast. The link works fine with Chrome in my emulator.

**Comment by mikemee** [comment]
Leave off the leading "@" and see how that works.  I just checked our code and it is:

```java
    private static final String TWITTER_USER_NAME = "eggheadgamesllc";
```
so the `@` is probably what's causing the problem.  FYI, you can see in the source at https://github.com/eggheadgames/android-about-box/blob/210c48d2ed9c6eb1d82b2ecddd7fca31956e8e5d/library/src/main/java/com/eggheadgames/aboutbox/AboutBoxUtils.java that is is actually calling:
```
Uri.parse("twitter://user?screen_name=" + name)
```
so you can test that in your browser as well.  

Please re-open if that doesn't fix things for you.

**Comment by Kvaibhav01** [comment]
That works! 😃
