### ISSUE TITLE
Remove cards from About Activity

### ISSUE THREAD

**Issue by Ninjaman494** [eggheadgames/android-about-box#47]
Is there a way to remove cards from About Activity? I know you can leave options null so that they don;t appear, but the an empty card will still appear. Can you remove the card entirely or do I need to implement it myself?

**Comment by mikemee** [comment]
Great question. If an option is null, that should remove the card. If you’d like to submit a PR for anything along those lines, I’ll definitely accept it. Thanks!

**Comment by Ninjaman494** [comment]
I took your advice and made a pull request to fix this. https://github.com/eggheadgames/android-about-box/pull/48

**Comment by mikemee** [comment]
@Ninjaman494 Wow, this took a long time, sorry. But we've just updated the library to the latest Android things and will add this shortly as well.
