### ISSUE TITLE
Privacy policy is not shown

### ISSUE THREAD

**Issue by im5an** [eggheadgames/android-about-box#49]
I recent use about box library 1.3.2 but i am not able to view privacy policy html when click on privacy policy,  I am loading privacy policy html path from assets folder and my second issue is that still empty card  is shown for appconfig.publisher which is set null

**Comment by mikemee** [comment]
We're working on the empty card issue. That's currently in #48 but might be moved to a new issue as there are conflicting updates.

Sorry, I have no idea about the privacy policy html.  If you have more info, please re-open this, thanks!
