### ISSUE TITLE
Facebook link do not open 

### ISSUE THREAD

**Issue by agos74** [eggheadgames/android-about-box#51]
Facebook link do not open facebook app with the correct page or profile url. 
It looks seem the code for facebook app is changed in the lastets versions. 
I have tried and it works with "fb://page/" + FACEBOOK_PAGE_ID.
The code in this library using this URI: "fb://profile/" + name
Look at this line inAboutBoxUtils.java: Intent intent = new Intent("android.intent.action.VIEW", Uri.parse("fb://profile/" + name));

Please can you update the code?

Thank you and i'm sorry for my bad english.

**Comment by mikemee** [comment]
Is anyone else seeing this?  Is there a reference to Facebook's change?  

I don't want to change it and then have it fail in other scenarios, so any other input would be helpful. Thanks!

**Comment by agos74** [comment]
I dont know where to find references to facebook's change but on stackoverflow i founded many posts with similar issues and solutions... like this: 
https://stackoverflow.com/questions/34564211/open-facebook-page-in-facebook-app-if-installed-on-android?noredirect=1&lq=1
or
https://stackoverflow.com/questions/54611453/how-to-open-profile-on-facebook-app-from-android-app

**Comment by mikemee** [comment]
Thanks @agos74 

This makes sense now that I have looked at the links. Sorry for taking so long to research this. Most of my test devices do not have Facebook installed, so it just opens the web browser which works as expected.

We are currently updating the library, so I will add this to the list of things to change and will use one of the suggestions given in that first link: https://stackoverflow.com/questions/34564211/open-facebook-page-in-facebook-app-if-installed-on-android?noredirect=1&lq=1

**Comment by mikemee** [comment]
@AlexDibrivnyy I think this might be the best one to copy. The other answers seem fairly old:

https://stackoverflow.com/a/44309106/19506

**Comment by agos74** [comment]
//method to get the right URL to use in the intent
    public static String getFacebookPageURL(Context context) {
        String FACEBOOK_URL = "https://www.facebook.com/AppSpiaggeSardegna";
        String FACEBOOK_PAGE_ID = "101578071197617";

        PackageManager packageManager = context.getPackageManager();
        try {
//            int versionCode = packageManager.getPackageInfo("com.facebook.katana", 0).versionCode;
//            Log.d("MainActivity" , "Version code: " + versionCode);
            boolean activated = packageManager.getApplicationInfo("com.facebook.katana", 0).enabled;
            if (activated) {
//                if (versionCode >= 3002850) { //newer versions of fb app
//                    return "fb://facewebmodal/f?href=" + FACEBOOK_URL;
//                } else { //older versions of fb app
                return "fb://page/" + FACEBOOK_PAGE_ID;
//                }
            } else {
                return FACEBOOK_URL; //normal web url
            }
        } catch (PackageManager.NameNotFoundException e) {
            return FACEBOOK_URL; //normal web url
        }
    }

**Comment by agos74** [comment]
In my app i used this similar code:

    //method to get the right URL to use in the intent
    public static String getFacebookPageURL(Context context) {
        String FACEBOOK_URL = "https://www.facebook.com/AppSpiaggeSardegna";
        String FACEBOOK_PAGE_ID = "101578071197617";

        PackageManager packageManager = context.getPackageManager();
        try {
            boolean activated = packageManager.getApplicationInfo("com.facebook.katana", 0).enabled;
            if (activated) {
                return "fb://page/" + FACEBOOK_PAGE_ID;
            } else {
                return FACEBOOK_URL; //normal web url
            }
        } catch (PackageManager.NameNotFoundException e) {
            return FACEBOOK_URL; //normal web url
        }
    }
